name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Runs when you push to main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Pull down your repo code
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build your Next.js app
      - name: Build
        run: npm run build

      # 5. Deploy build to Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for PR integration
          action: "upload"
          app_location: "/"        # your project root
          api_location: ""         # leave empty unless you have an API
          output_location: ".next" # Next.js build output folder